[package]
name = "dynamic_reload"
version = "0.3.0"
license = "MIT/Apache-2.0"
authors = ["Daniel Collin <daniel@collin.com>"]
description = "Cross-platform dynamic reloading of shared libraries"
keywords = ["dynamic", "addins", "plugins", "reload", "sharedlibrary"]
repository = "https://github.com/emoon/dynamic_reload"
homepage = "https://github.com/emoon/dynamic_reload"
documentation = "https://docs.rs/dynamic_reload"
build = "build.rs"
readme = "README.md"

[dependencies]
notify = "^2.5.0"
libc = "0.2.0"
libloading = "0.3.0"
tempdir = "0.3"

